server:
  servlet:
    context-path: /api/v1

spring:
  datasource:
    username: <changeit>
    password: <changeit>
    url: <changeit>
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate